#!/bin/bash -e

source $OPENSHIFT_CARTRIDGE_SDK_BASH


function jruby-install() {
  echo "Installing JRuby..."

  # needed in order to support scaling
  if [ "$OPENSHIFT_JRUBY_VERSION" == "" ]
  then
    export OPENSHIFT_JRUBY_VERSION=`curl http://jruby.org/download | ruby -e "s=ARGF.read;x=/Current Release: JRuby (\d\.\d\.\d.\d)/m.match(s);puts x[1]"`
  fi

  echo "$OPENSHIFT_JRUBY_VERSION" > ${OPENSHIFT_JRUBY_DIR}env/OPENSHIFT_JRUBY_VERSION

  pushd ${OPENSHIFT_RUBY_DIR}/tmp 1>/dev/null
  
  curl -o jruby.tar.gz https://s3.amazonaws.com/jruby.org/downloads/$OPENSHIFT_JRUBY_VERSION/jruby-bin-$OPENSHIFT_JRUBY_VERSION.tar.gz

  tar xf jruby.tar.gz
  rm -rf jruby.tar.gz
  mkdir -p ${OPENSHIFT_DEPENDENCIES_DIR}/.gem-jruby/bin
  mkdir -p ${OPENSHIFT_RUBY_DIR}/.jruby/

  # jruby executables are stored in ~/.jruby/jruby-${OPENSHIFT_JRUBY_VERSION}/
  mv jruby-${OPENSHIFT_JRUBY_VERSION} ${OPENSHIFT_RUBY_DIR}/.jruby/jruby-${OPENSHIFT_JRUBY_VERSION}

  chmod +x ${OPENSHIFT_RUBY_DIR}/versions/shared/jruby
  ln -s ${OPENSHIFT_RUBY_DIR}/versions/shared/jruby ${OPENSHIFT_RUBY_DIR}/.jruby/jruby

  install-required-gems

  echo "JRuby installed."

  return 0
}

function install-required-gems() {
  echo "Installing required jems for JRuby"
  curl https://rubygems.org/downloads/bundler-1.11.2.gem
  curl https://rubygems.org/downloads/rake-10.5.0.gem
  ${OPENSHIFT_RUBY_DIR}/.jruby/jruby -S gem install bundler rake --local
  return 0
}